name: Other
description: Open a general issue
title: Other Issue Title
body:
  - type: markdown
    attributes:
      value: |
        **READ THIS FIRST**

        This form should almost **NEVER** be used. Consider closely why your issue does not fit into one of the [other categories](https://github.com/ethers-io/ethers.js/issues/new/choose).
        
        You almost certainly wish to use [the discussions](https://github.com/ethers-io/ethers.js/discussions) instead, to ask a question or seek further guidance.
  - type: textarea
    id: about
    attributes:
      label: Describe your Issue
      description: Please include as much relevant context as possible, be concise and clearly explain what you are looking for.
      placeholder: e.g. What is the answer to life, the universe and everything?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: This is an exception issue
      description: This form is **only** for *exceptional issues*, which do not match any [other categoeries](https://github.com/ethers-io/ethers.js/issues/new/choose).
      options:
        - label: I understand this form is for exceptional issues and believe my issue qualifies.
          required: true
